# Name of the workflow
# This is what you see in the GitHub Actions tab
name: Deploy on laptop

# When should this workflow run?
# 'push' means it runs every time code is pushed to the repository
on:
  push:

# A workflow is made up of one or more jobs
jobs:

  # Job name (can be any name)
  build:

    # The type of machine that will run this job
    # GitHub provides a temporary Ubuntu Linux machine
    runs-on: ubuntu-latest

    # A job consists of multiple steps
    steps:

      # Step 1: Download (clone) the repository code
      # Without this step, the runner would not have your files
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Install Python on the runner
      # This sets up a Python environment for the workflow
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      # Step 3: Install project dependencies
      # pip is upgraded first, then packages from requirements.txt are installed
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      # Step 4: Run unit tests (pytest)
      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=${{ github.workspace }}" >> $GITHUB_ENV
      - name: Run tests
        run: pytest -q
      - name: deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12                          
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}          
          heroku_app_name: "wedc"       
          heroku_email: "afarahan@nu.edu"



